aa_abr = {'A': 'Ala',
          'C': 'Cys',
          'D': 'Asp',
          'E': 'Glu',
          'F': 'Phe',
          'G': 'Gly',
          'H': 'His',
          'I': 'Ile',
          'K': 'Lys',
          'L': 'Leu',
          'M': 'Met',
          'N': 'Asn',
          'P': 'Pro',
          'Q': 'Gln',
          'R': 'Arg',
          'S': 'Ser',
          'T': 'Thr',
          'V': 'Val',
          'W': 'Trp',
          'Y': 'Tyr'}

aa_classes = {'A': ['S', 'hydrophobic', '0'],
              'C': ['S', 'hydrophobic', '0'],
              'D': ['S', 'hydrophylic', '-'],
              'E': ['M', 'hydrophylic', '-'],
              'F': ['L', 'hydrophobic', '0'],
              'G': ['S', 'inbetween', '0'],
              'H': ['M', 'inbetween', '+'],
              'I': ['L', 'hydrophobic', '0'],
              'K': ['L', 'hydrophylic', '+'],
              'L': ['L', 'hydrophobic', '0'],
              'M': ['L', 'hydrophobic', '0'],
              'N': ['S', 'hydrophylic', '0'],
              'P': ['S', 'inbetween', '0'],
              'Q': ['M', 'hydrophylic', '0'],
              'R': ['L', 'hydrophylic', '+'],
              'S': ['S', 'inbetween', '0'],
              'T': ['S', 'inbetween', '0'],
              'V': ['M', 'hydrophobic', '0'],
              'W': ['L', 'hydrophobic', '0'],
              'Y': ['L', 'inbetween', '0']}

aa_colours = {'A': 'green',
              'C': 'goldenrod',
              'D': 'red',
              'E': 'tomato',
              'F': 'sandybrown',
              'G': 'hotpink',
              'H': 'purple',
              'I': 'sienna',
              'K': 'darkorchid',
              'L': 'olive',
              'M': 'yellow',
              'N': 'blue',
              'P': 'limegreen',
              'Q': 'turquoise',
              'R': 'plum',
              'S': 'steelblue',
              'T': 'navy',
              'V': 'chocolate',
              'W': 'saddlebrown',
              'Y': 'yellowgreen'}
